
# Name your project! Project names should contain only lowercase characters
# and underscores. A good package name should reflect your organization's
# name or the intended use of these models
name: 'dbt_lab_project'
version: '1.0.0'
config-version: 2

# This setting configures which "profile" dbt uses for this project.
profile: 'default'

# These configurations specify where dbt should look for different types of files.
# The `model-paths` config, for example, states that models in this project can be
# found in the "models/" directory. You probably won't need to change these!
model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"  # directory which will store compiled SQL files
clean-targets:         # directories to be removed by `dbt clean`
  - "target"
  - "dbt_packages"


# Configuring models
# Full documentation: https://docs.getdbt.com/docs/configuring-models

# In dbt, the default materialization for a model is a view. This means, when you run 
# dbt run or dbt build, all of your models will be built as a view in your data platform. 
# The configuration below will override this setting for models in the example folder to 
# instead be materialized as tables. Any models you add to the root of the models folder will 
# continue to be built as views. These settings can be overridden in the individual model files
# using the `{{ config(...) }}` macro.

models:
  dbt_lab_project:
    # Applies to all files under models/example/
    example:
      +materialized: view
    raw:
      +materialized: table
      orders_incremental_append:             # model name (orders.sql)
        +materialized: incremental
        +incremental_strategy: append
      orders_incremental_merge:             # model name (orders.sql)
        +materialized: incremental
        +incremental_strategy: merge
      orders_incremental_delete_insert:
        +materialized: incremental
        +incremental_strategy: delete+insert
      orders_insert_overwrite:
        +materialized: incremental
        +incremental_strategy: insert_overwrite
      country_status:        # override config for this model only
        +materialized: view  # override materialization to 'view'
        +database: DBT_CLEAN # assign a different database
        +schema: CLEAN_SCHEMA  # optional if you want to change schema
    silver:
      +database: DBT_LABS
      +schema: SILVER_SCH
      +materialized: table
    Gold:
      +schema: clean_schema
      +database: DBT_CLEAN
      +materialized: view

seeds:
  dbt_lab_project:
    +enabled: true
    +schema: CLEAN_SCHEMA
    +database: DBT_CLEAN
  
    country_info: #default it will take as ',' seperator
      +column_types:
        country_code: varchar(100)
        country_name: varchar(100)
        region: varchar(100)
        currency: varchar(100)
        language: varchar(100)
    country_popluation:
    country_internet:
      +delimiter: '|'
      +schema: CLEAN_SCHEMA
      +column_types:
        country_code: varchar(100)
        internet_users_millions: number
        mobile_subscriptions_millions: number
        sim_card_prefix: varchar(10)
      

