version: 2

sources:
  - name: raw_data
    schema: SF_SCHEMA
    database: SNOWFLAKE_DBT_DATA
    tables:
      - name: CUSTOMER
  - name: prod_data
    schema: PROD_SCH
    database: SNOWFLAKE_DBT_DATA
    tables:
      - name: PRODUCT
  - name : sale_data
    schema: SF_SCHEMA
    database: SNOWFLAKE_DBT_DATA
    tables:
      - name: SALES_TRANSACTIONS
  - name : order_data
    schema: SF_SCHEMA
    database: SNOWFLAKE_DBT_DATA
    tables :
      - name: orders
  - name: supply_data
    schema: SF_SCHEMA
    database: SNOWFLAKE_DBT_DATA
    tables:
      - name: SUPPLY_CHAIN_ORDERS
  - name: tele_customer
    schema: SF_SCHEMA
    database: SNOWFLAKE_DBT_DATA
    tables:
      - name: TELECOM_CUSTOMERS
  - name: tele_telecom_plans
    schema: SF_SCHEMA
    database: SNOWFLAKE_DBT_DATA
    tables:
      - name: TELE_PLANS
        identifier: TELECOM_PLANS
